// Row shapes, hand-written to match supabase/migrations.
//
// Not generated from the database on purpose, for now: a generated file is
// regenerated by whoever remembers, and this schema is small enough that a
// mismatch shows up as a TypeScript error on the next edit. If the table count
// doubles, switch to `supabase gen types`.

export type SpecKind = 'number' | 'bool' | 'enum' | 'text';
export type PrintColorModel = 'spot' | 'full_color' | 'single_tone' | 'thread';

/**
 * A Postgres `numeric` as it arrives over PostgREST.
 *
 * Typed as the union deliberately rather than guessed at: PostgREST emits
 * numeric as a JSON number, but a client, a view or a future RPC can hand back
 * a string, and the difference between 52.5 and "52.5" is a silently wrong
 * total. Everything downstream goes through Number() or formatAmount(), both
 * of which take either.
 */
export type Numeric = number | string;

export interface Category {
  id: string;
  slug: string;
  name_ar: string;
  name_en: string | null;
  blurb_ar: string | null;
  icon: string | null;
  cover_url: string | null;
  parent_id: string | null;
  sort_order: number;
  is_active: boolean;
  seo_title_ar: string | null;
  seo_desc_ar: string | null;
}

export interface Occasion {
  id: string;
  slug: string;
  name_ar: string;
  name_en: string | null;
  blurb_ar: string | null;
  cover_url: string | null;
  starts_on: string | null;
  ends_on: string | null;
  sort_order: number;
  is_active: boolean;
  seo_title_ar: string | null;
  seo_desc_ar: string | null;
}

export interface PriceTier {
  min_qty: number;
  unit_price: Numeric;
}

export interface PrintMethod {
  code: string;
  name_ar: string;
  name_en: string | null;
  blurb_ar: string | null;
  color_model: PrintColorModel;
  needs_vector: boolean;
  default_setup_fee: Numeric;
  default_max_colors: number | null;
  sort_order: number;
  is_active: boolean;
}

export interface ProductPrintMethod {
  method_code: string;
  setup_fee: Numeric;
  setup_fee_per_color: boolean;
  setup_fee_waived_over_qty: number | null;
  unit_addon: Numeric;
  addon_per_color: Numeric;
  max_colors: number | null;
  method_min_qty: number | null;
  is_default: boolean;
  print_methods: PrintMethod | null;
}

export interface PrintPosition {
  id: string;
  code: string;
  name_ar: string;
  name_en: string | null;
  area_w_mm: Numeric | null;
  area_h_mm: Numeric | null;
  preview_x: Numeric | null;
  preview_y: Numeric | null;
  preview_w: Numeric | null;
  preview_h: Numeric | null;
  preview_rotate: Numeric;
  is_default: boolean;
  sort_order: number;
}

export interface OptionItem {
  id: string;
  value: string;
  label_ar: string;
  hex: string | null;
  price_delta: Numeric;
  is_available: boolean;
  image_url: string | null;
  sort_order: number;
}

export interface OptionGroup {
  id: string;
  code: string;
  label_ar: string;
  is_required: boolean;
  sort_order: number;
  product_option_items: OptionItem[];
}

export interface ProductImage {
  id: string;
  url: string;
  alt_ar: string | null;
  option_item_id: string | null;
  sort_order: number;
}

export interface SpecDef {
  key: string;
  label_ar: string;
  unit_ar: string | null;
  kind: SpecKind;
  is_filterable: boolean;
  show_in_card: boolean;
  is_key: boolean;
  section_ar: string | null;
  sort_order: number;
}

/** Every spec column, so `product[specKey]` type-checks instead of needing `any`. */
export interface ProductSpecColumns {
  material_ar: string | null;
  dimensions_ar: string | null;
  weight_g: number | null;
  capacity_ml: number | null;
  paper_gsm: number | null;
  page_count: number | null;
  usb_capacity_gb: number | null;
  battery_mah: number | null;
  pack_size: number | null;
  warranty_months: number | null;
  origin_ar: string | null;
  is_eco: boolean | null;
}

export type SpecValue = string | number | boolean | null;

export interface ProductCardRow extends ProductSpecColumns {
  id: string;
  slug: string;
  name_ar: string;
  short_pitch_ar: string | null;
  cover_url: string | null;
  moq: number;
  price_at_moq: Numeric | null;
  price_from: Numeric | null;
  for_corporate: boolean;
  for_individual: boolean;
  is_available: boolean;
  is_featured: boolean;
  category_id: string;
  sort_order: number;
  created_at: string;
}

export interface ProductDetailRow extends ProductCardRow {
  name_en: string | null;
  sku: string | null;
  description_ar: string | null;
  max_positions: number;
  max_text_lines: number;
  allows_logo: boolean;
  allows_text: boolean;
  lead_days_min: number | null;
  lead_days_max: number | null;
  extra_specs: Record<string, string>;
  seo_title_ar: string | null;
  seo_desc_ar: string | null;
  categories: Pick<Category, 'id' | 'slug' | 'name_ar'> | null;
  product_price_tiers: PriceTier[];
  product_print_methods: ProductPrintMethod[];
  print_positions: PrintPosition[];
  product_option_groups: OptionGroup[];
  product_images: ProductImage[];
}

export interface SiteSettings {
  brand_name_ar: string;
  brand_name_en: string | null;
  tagline_ar: string | null;
  whatsapp_phone: string | null;
  hotline: string | null;
  email: string | null;
  address_ar: string | null;
  maps_url: string | null;
  working_hours_ar: string | null;
  currency: string;
  vat_rate: Numeric;
  prices_include_vat: boolean;
  artwork_service_fee: Numeric | null;
  min_order_value: Numeric | null;
  quote_promise_ar: string | null;
  rush_note_ar: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  tiktok_url: string | null;
  linkedin_url: string | null;
  og_default_image: string | null;
}
