// Refuses source that imports a file git does not have.
//
// THE BUG THIS EXISTS FOR, because it cost a production deploy:
//
//   web/lib/queries.preview.ts imports web/preview-data.json.
//   The .json is GENERATED by tools/preview/dump.mjs and .gitignore keeps it
//   out of the repository, correctly — it is output, not source.
//
//   On the machine that generated it, `next build` passed. On the build host it
//   did not exist, and the deploy died with "Cannot find module". The failure
//   was invisible in every local check precisely because the local machine is
//   the one place the file is guaranteed to be.
//
// A build is only trustworthy if it depends on nothing outside git. This walks
// every tracked source file, resolves its local imports, and fails if any of
// them lands on a file git has never seen.
//
//   node tools/web-check/tracked-imports.mjs

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');

/** Everything git tracks, as a set of repo-relative POSIX paths. */
const tracked = new Set(
  execFileSync('git', ['ls-files'], { cwd: root, encoding: 'utf8' })
    .split('\n')
    .filter(Boolean)
);

// Only files git tracks can be checked — an untracked file is not part of what
// the build host receives, so what it imports is irrelevant.
const sources = [...tracked].filter(
  (f) => f.startsWith('web/') && /\.(ts|tsx|js|jsx|mjs)$/.test(f) && !f.includes('node_modules')
);

// tsconfig maps '@/x' to the web/ directory.
const ALIAS = { '@/': 'web/' };
const EXTENSIONS = ['', '.ts', '.tsx', '.js', '.jsx', '.mjs', '.json', '/index.ts', '/index.tsx'];

// Excluded from type-checking AND from the shipped bundle. It is allowed to
// import the generated dump, because the build never reads it — see the exclude
// block in web/tsconfig.json.
const EXEMPT = new Set(['web/lib/queries.preview.ts']);

const problems = [];

for (const file of sources) {
  if (EXEMPT.has(file)) continue;
  const text = readFileSync(join(root, file), 'utf8');

  const specifiers = [
    ...text.matchAll(/(?:from|import)\s+['"]([^'"]+)['"]/g),
    ...text.matchAll(/import\(\s*['"]([^'"]+)['"]\s*\)/g),
  ].map((m) => m[1]);

  for (const spec of specifiers) {
    const isAlias = spec.startsWith('@/');
    const isRelative = spec.startsWith('./') || spec.startsWith('../');
    if (!isAlias && !isRelative) continue; // a package, not our file

    const target = isAlias
      ? spec.replace('@/', ALIAS['@/'])
      : relative(root, resolve(dirname(join(root, file)), spec)).split('\\').join('/');

    const resolved = EXTENSIONS.map((e) => `${target}${e}`).find((c) => tracked.has(c));
    if (resolved) continue;

    // Distinguish the two failures: a file that is simply missing is a typo; a
    // file that exists on THIS disk but not in git is the dangerous one, because
    // it will build here and nowhere else.
    const onDisk = EXTENSIONS.some((e) => existsSync(join(root, `${target}${e}`)));
    problems.push({ file, spec, onDisk });
  }
}

for (const p of problems) {
  console.log(
    `FAIL  ${p.file}\n      imports "${p.spec}" — ` +
      (p.onDisk
        ? 'the file is on this disk but NOT in git, so it will build here and fail on the build host'
        : 'no such file')
  );
}

console.log(
  problems.length === 0
    ? `PASS  tracked-imports — ${sources.length} files, every local import is in git`
    : `\n${problems.length} import(s) point outside git`
);
process.exit(problems.length ? 1 : 0);
