// أشكال الصفوف — مكتوبة باليد لتطابق supabase/migrations/2026081210*.
//
// Same call as web/lib/types.ts: not generated, because a generated file is
// regenerated by whoever remembers, and a mismatch here shows up as a
// TypeScript error on the next edit.

export type StaffRole = 'doctor' | 'reception' | 'director';
export type RecordStatus = 'draft' | 'issued' | 'cancelled';
export type VisitStatus =
  | 'booked' | 'waiting' | 'in_room' | 'done' | 'no_show' | 'cancelled';
export type VisitKind = 'new' | 'follow_up';
export type PayMethod = 'cash' | 'instapay' | 'card' | 'other';

/** Postgres numeric over PostgREST — see the note in web/lib/types.ts. */
export type Numeric = number | string;

export interface ClinicStaff {
  id: string;
  role: StaffRole;
  display_name: string;
  phone: string | null;
  title_ar: string | null;
  specialty_ar: string | null;
  syndicate_no: string | null;
  rx_prefix: string | null;
  is_active: boolean;
  created_at?: string;
}

export interface ClinicSettings {
  clinic_name_ar: string;
  address_ar: string | null;
  phone: string | null;
  whatsapp_phone: string | null;
  working_hours_ar: string | null;

  header_offset_mm: Numeric;
  footer_offset_mm: Numeric;
  margin_x_mm: Numeric;
  print_header: boolean;

  consult_fee: Numeric;
  follow_up_fee: Numeric;
  follow_up_days: number;
  currency: string;

  drug_catalog_version: number;
}

export interface Patient {
  id: string;
  /** null until the row has reached the server — see clinic.sync_patient(). */
  file_no: number | null;
  full_name: string;
  phone: string | null;
  gender: 'male' | 'female' | null;
  birth_date: string | null;
  address_ar: string | null;
  allergies_ar: string | null;
  chronic_ar: string | null;
  notes_ar: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface Drug {
  id: string;
  trade_name: string;
  /** The brand as an Arabic-typing doctor spells it: "كونكور" for Concor. */
  trade_name_ar: string;
  generic_ar: string | null;
  generic_en: string | null;
  form_ar: string;
  strength: string;
  /** Folded server-side by public.fold_arabic(); the device searches on this. */
  name_key: string;
  is_active: boolean;
}

export interface LabTest {
  id: string;
  name_ar: string;
  name_en: string | null;
  category: string;
  name_key: string;
  is_active: boolean;
}

export interface RxItem {
  line_no?: number;
  drug_id: string | null;
  drug_name: string;
  form_ar: string | null;
  strength: string | null;
  dose_ar: string | null;
  frequency_ar: string | null;
  duration_ar: string | null;
  route_ar: string | null;
  notes_ar: string | null;
}

export interface Prescription {
  id: string;
  patient_id: string;
  encounter_id: string | null;
  doctor_id: string;
  rx_no: string;
  status: RecordStatus;
  issued_at: string | null;
  printed_count: number;
  amended_from: string | null;
  amend_reason: string | null;
  written_at: string;
  /** Joined by clinic.patient_file(); absent on a locally-written draft. */
  doctor_name?: string;
  superseded?: boolean;
  items: RxItem[];
}

export interface Encounter {
  id: string;
  patient_id: string;
  visit_id: string | null;
  doctor_id: string;
  temp_c: Numeric | null;
  pulse: number | null;
  bp_sys: number | null;
  bp_dia: number | null;
  weight_kg: Numeric | null;
  height_cm: Numeric | null;
  complaint_ar: string | null;
  history_ar: string | null;
  exam_ar: string | null;
  diagnosis_ar: string | null;
  plan_ar: string | null;
  next_visit_on: string | null;
  status: RecordStatus;
  doctor_name?: string;
  created_at?: string;
}

export interface QueueRow {
  visit_id: string;
  patient_id: string;
  file_no: number | null;
  full_name: string;
  phone: string | null;
  doctor_id: string | null;
  doctor_name: string | null;
  status: VisitStatus;
  kind: VisitKind;
  fee: Numeric;
  scheduled_at: string | null;
  arrived_at: string | null;
  paid: Numeric;
}

export interface PatientSearchRow {
  id: string;
  file_no: number | null;
  full_name: string;
  phone: string | null;
  gender: 'male' | 'female' | null;
  birth_date: string | null;
  allergies_ar: string | null;
  chronic_ar: string | null;
  last_visit: string | null;
}

export interface PatientFile {
  patient: Patient;
  encounters: Encounter[];
  prescriptions: Prescription[];
}

export interface HomeCounts {
  waiting: number;
  in_room: number;
  mine_today: number;
  done_today: number;
  patients: number;
  unreviewed: number;
}

export interface DoctorReportRow {
  doctor_id: string;
  doctor_name: string;
  visits: number;
  patients: number;
  encounters: number;
  prescriptions: number;
  due: Numeric;
  collected: Numeric;
}
